// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXdNyNRk8-dVet0nXSZH7t3cvGDvlUlUU',
    appId: '1:139303566650:web:b8764cade2456674b12403',
    messagingSenderId: '139303566650',
    projectId: 'just-3-1ebd9',
    authDomain: 'just-3-1ebd9.firebaseapp.com',
    storageBucket: 'just-3-1ebd9.firebasestorage.app',
    measurementId: 'G-XSR053EV3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOiQvccvTIU9X-tFC0FRu_XOluRTGugo',
    appId: '1:139303566650:android:655f8bf38f6fdd8bb12403',
    messagingSenderId: '139303566650',
    projectId: 'just-3-1ebd9',
    storageBucket: 'just-3-1ebd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDilzunLgrT52WTXnsOFZ_sFDG7cySignI',
    appId: '1:139303566650:ios:2a3ab272eae70db4b12403',
    messagingSenderId: '139303566650',
    projectId: 'just-3-1ebd9',
    storageBucket: 'just-3-1ebd9.firebasestorage.app',
    iosBundleId: 'com.example.just3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDilzunLgrT52WTXnsOFZ_sFDG7cySignI',
    appId: '1:139303566650:ios:2a3ab272eae70db4b12403',
    messagingSenderId: '139303566650',
    projectId: 'just-3-1ebd9',
    storageBucket: 'just-3-1ebd9.firebasestorage.app',
    iosBundleId: 'com.example.just3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXdNyNRk8-dVet0nXSZH7t3cvGDvlUlUU',
    appId: '1:139303566650:web:dd11b6d6aeefd9eab12403',
    messagingSenderId: '139303566650',
    projectId: 'just-3-1ebd9',
    authDomain: 'just-3-1ebd9.firebaseapp.com',
    storageBucket: 'just-3-1ebd9.firebasestorage.app',
    measurementId: 'G-E9LZY9YQXF',
  );
}
